### ISSUE TITLE
[Bug Report] Prosecutor doesn't turn into a Pursuer if their target gets Guessed in meeting.

### ISSUE THREAD

**Issue by JustASysAdmin** [JustASysAdmin/TheOtherRoles2#11]
**Describe the bug**
Prosecutor doesn't turn into a Pursuer if their target gets Guessed in meeting.

**To Reproduce**
Guess Prosecutor target as the correct role.

**Expected behavior**
The Prosecutor turns into Pursuer

**Comment by Scoooom** [comment]
Fixed in bc3794a3b7b622752552bc014c89a01549db9b3a
