### ISSUE TITLE
[Bug Report] Cultist can be guessed, but is hard disabled

### ISSUE THREAD

**Issue by XiezibanWrite** [JustASysAdmin/TheOtherRoles2#63]
Cultist this occupation is not can be set, but can be gambling monster guessing, in the last few versions, the impact is great, I hope it can be fixed.

**Comment by Scoooom** [comment]
Need to remove cultist from the roleinfo list

**Comment by Scoooom** [comment]
I will fix this in 5.7.0

**Comment by Scoooom** [comment]
Fixed in 17cf4a0f925d9caf7d5473a63ab861891f0de3bf
